### PR TITLE
remove wrong (and redundant) IsIpv6LinkLocal

### LINKED ISSUE #169: wrong IsIpv6LinkLocal
This change https://github.com/multiformats/go-multiaddr/pull/168#discussion_r772750843 was wrong. It's doing the exact opposite of what the name suggests.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #169.

We should just use `IsIP6LinkLocal` instead.

### CODE REVIEW

File: net/resolve.go [hunk 1]
```diff
@@ -74,7 +74,7 @@ func interfaceAddresses() ([]ma.Multiaddr, error) {
 
 	var out []ma.Multiaddr
 	for _, a := range maddrs {
-		if !IsIpv6LinkLocal(a) {
+		if IsIP6LinkLocal(a) {
```
Comment (marten-seemann) [inline net/resolve.go:77]: Note that `IsIpv6Local` was doing the opposite of what the name suggested.

**Review by Stebalien — APPROVED** [review]
